from typing import Any
import sys
import os
import tempfile
from git import Repo

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))
from mcp_server.tools.git_tools import (
    create_branch,
    apply_patch_and_commit,
    push_branch,
    create_pull_request
)
from agent.state import PipelineState

def apply_fix_node(state: PipelineState) -> dict[str, Any]:
    try:
        pat = state.get("github_pat")
        repo_name = state.get("repo")
        proposed_patch = state.get("proposed_patch", {})
        
        if not pat or not repo_name:
            return {"error": "Missing github_pat or repo in state", "current_step": "error"}
            
        if not proposed_patch:
            return {"error": "No patch to apply", "current_step": "error"}

        branch_name = f"pipelinepilot/fix-{state.get('failed_run_id', 'unknown')}"
        
        # Create temp dir and clone repo
        temp_dir = tempfile.mkdtemp()
        repo_url = f"https://{pat}@github.com/{repo_name}.git"
        
        # Clone repo
        Repo.clone_from(repo_url, temp_dir)
        
        # Create branch
        res = create_branch(repo_path=temp_dir, branch_name=branch_name)
        if not res.get("success"):
            return {"error": f"Failed to create branch: {res.get('message')}", "current_step": "error"}
            
        # Apply patches and commit
        root_cause = state.get("root_cause", "pipeline failure")
        commit_message = f"fix: {root_cause[:72]} [PipelinePilot]"
        
        last_commit_sha = None
        for filepath, patch_data in proposed_patch.items():
            patched_content = patch_data.get("patched")
            res = apply_patch_and_commit(
                repo_path=temp_dir,
                file_path=filepath,
                new_content=patched_content,
                commit_message=commit_message,
                branch_name=branch_name
            )
            if not res.get("success"):
                return {"error": f"Failed to apply patch to {filepath}: {res.get('message')}", "current_step": "error"}
            last_commit_sha = res.get("commit_sha")
            
        # Push branch
        res = push_branch(repo_path=temp_dir, branch_name=branch_name, github_pat=pat)
        if not res.get("success"):
            return {"error": f"Failed to push branch: {res.get('message')}", "current_step": "error"}
            
        # Create PR
        pr_title = f"Fix: Pipeline Failure #{state.get('failed_run_id', '')}"
        pr_body = f"## Root Cause Analysis\n{root_cause}\n\n## Fix Applied\n{state.get('patch_explanation', '')}\n\n*Generated by PipelinePilot*"
        res = create_pull_request(
            github_pat=pat,
            repo=repo_name,
            title=pr_title,
            body=pr_body,
            head_branch=branch_name
        )
        if not res.get("success"):
            return {"error": f"Failed to create PR: {res.get('message')}", "current_step": "error"}
            
        return {
            "branch_name": branch_name,
            "commit_sha": last_commit_sha,
            "pr_url": res.get("pr_url"),
            "current_step": "fix_applied"
        }

    except Exception as e:
        return {"error": f"Failed in apply_fix_node: {str(e)}", "current_step": "error"}
